version: "3"
services:

  app:
    build:
      context: .
      dockerfile: development.dockerfile
    ports:
      - 3000:3000
      - 3449:3449
      - 7000:7000
      - 7002:7002
    user: "${UID}:0"
    volumes:
      - .:/usr/app/time-align
      - ./.lein:/.lein
    working_dir: /usr/app/time-align
    command: ["lein", "repl", ":headless", ":host", "0.0.0.0", ":port", "7000"]

    # command: ["lein", "uberjar"] # compile the jar

    # command: ["java", "-jar","target/uberjar/time-align.jar"] # test run the compiled jar locally
    # environment:
    #   DATABASE_URL: "postgresql://db/time_align?user=time_align&password=time_align" # needed to test run jar

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: time_align
      POSTGRES_USER: time_align



